version: '3.8'

services:
  # 1. Laravel Application Container
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always
    ports:
      - "8000:80"
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_KEY: "base64:79diLxbM3/y28VpmB5guR0XKk8FSz8BMGXgWg3qu8ko=" # Agar aapki key hai toh yahan likhein
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1                            # Service name 'db' yahan host banegi
      DB_PORT: 3306
      DB_DATABASE: devops-assesment          # Aapka database name
      DB_USERNAME: root
      DB_PASSWORD: Zain@12345
    depends_on:
      db:
        condition: service_healthy          # Pehle DB ready hoga, phir App start hogi

  # 2. MySQL Database Container
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: devops-assesment       # Automatic yeh database create hoga
      MYSQL_ROOT_PASSWORD: Zain@12345      # DB ka root password
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:                             # DB ke ready hone ka wait karta hai
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
